CREATE TABLE IF NOT EXISTS tasks_table (
  id INT AUTO_INCREMENT PRIMARY KEY,
  description VARCHAR(255) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'TO_DO',
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);