server:
  port: 8888

spring:
  application:
    name: github-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/artsemrogovenko/server-config.git
          basedir: file://c:/tmp/desk
          default-label: main

logging:
  level:
    org.springframework.cloud.config: DEBUG