server:
  port: 3869

spring:
  application:
    name: transfer

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update

  profiles:
    active: eclient



  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

  datasource:
    url: jdbc:h2:mem:accounts
    driverClassName: org.h2.Driver

    username: sa
    password: sa

  h2:
    console:
      enabled: true
